build: off
shallow_clone: false
platform: 'x64'
clone_folder: c:\projects\php-project-workspace

environment:
  matrix:
    - PHP_VERSION: "5.6"
    - PHP_VERSION: "7.3"
    - PHP_VERSION: "7.4"

cache:
  # Cache php install
  - c:\tools\php -> .appveyor.yml

install:
  - ps: Invoke-WebRequest "https://raw.githubusercontent.com/ChadSikorra/ps-install-php/master/Install-PHP.ps1" -OutFile "Install-PHP.ps1"
  - ps: .\Install-PHP.ps1 -Version $Env:PHP_VERSION -Highest -Arch x64 -Extensions openssl mbstring
  - refreshenv
  - cd C:\projects\php-project-workspace
  - php -r "readfile('https://getcomposer.org/installer');" | php

before_test:
  - cd C:\projects\php-project-workspace
  - php composer.phar install --no-interaction

test_script:
  - cd c:\projects\php-project-workspace
  - vendor/bin/phpunit